export const lightTheme = {
    media: {
        mobileS: '(max-width: 360px)',
        phone: '(max-width: 590px)',
        tablet: '(max-width: 768px)',
        smallLaptop: '(max-width: 1280px)',
    },
    colors: {
        main_color: '#F17900',
        main_opacity_color: ' rgba(241, 121, 0, 0.5)',
        second_color: '#27355A',
        main_text_color: '#2E266F',
        second_text_color: '#2E266F',
    },
    margin: {
        XXL: '200px',
        XL: '100px',
        L: '75px',
        LM: '70px',
        M: '60px',
        MS: '65px',
        S: '50px',
        XS: '40px',
        auto: 'auto',
        XXS: '25px',
        XXXS: '20px',
        SM: '30px',
        XSM: '10px',
        none: '0',
    },
    padding: {
        XL: '60px',
        L: '50px',
        M: '40px',
        S: '20px',
        XS: '15px',
        XXS: '10px',
        none: '0',
    },
};

export const darkTheme = {
    media: {
        mobileS: '(max-width: 360px)',
        phone: '(max-width: 590px)',
        tablet: '(max-width: 768px)',
        smallLaptop: '(max-width: 1280px)',
    },
    colors: {
        main_color: '#27355A',
        main_opacity_color: ' #27355A',
        second_color: '#F17900',
        main_text_color: '#2E266F',
        second_text_color: '#FFFFFF',
    },
    margin: {
        XXL: '200px',
        XL: '100px',
        L: '75px',
        LM: '70px',
        M: '60px',
        MS: '65px',
        S: '50px',
        XS: '40px',
        auto: 'auto',
        XXS: '25px',
        XXXS: '20px',
        SM: '30px',
        XSM: '10px',
        none: '0',
    },
    padding: {
        XL: '60px',
        L: '50px',
        M: '40px',
        S: '20px',
        XS: '15px',
        XXS: '10px',
        none: '0',
    },
};
