export const lightTheme = {
    media: {
        mobileS: '(max-width: 360px)',
        phone: '(max-width: 590px)',
        tablet: '(max-width: 768px)',
        smallLaptop: '(max-width: 1280px)',
    },
    colors: {
        primary_color: 'rgb(255, 255, 255)',
        main_color: 'rgb(241, 121, 0)',
        main_opacity_color: 'rgba(241, 121, 0, 0.5)',
        second_color: 'rgb(39, 53, 90)',
        main_text_color: 'rgb(46, 38, 111)',
        second_text_color: 'rgb(46, 38, 111)',
    },
    margin: {
        XXL: '200px',
        XL: '100px',
        L: '75px',
        LM: '70px',
        M: '60px',
        MS: '65px',
        S: '50px',
        XS: '40px',
        auto: 'auto',
        XXS: '25px',
        XXXS: '20px',
        SM: '30px',
        XSM: '10px',
        none: '0',
    },
    padding: {
        XL: '60px',
        L: '50px',
        M: '40px',
        S: '20px',
        XS: '15px',
        XXS: '10px',
        none: '0',
    },
};

export const darkTheme = {
    media: {
        mobileS: '(max-width: 360px)',
        phone: '(max-width: 590px)',
        tablet: '(max-width: 768px)',
        smallLaptop: '(max-width: 1280px)',
    },
    colors: {
        primary_color: 'rgb(0, 0, 0)',
        main_color: 'rgb(39, 53, 90)',
        main_opacity_color: 'rgba(39, 53, 90, 1)',
        second_color: 'rgb(241, 121, 0)',
        main_text_color: 'rgb(46, 38, 111)',
        second_text_color: 'rgb(255, 255, 255)',
    },
    margin: {
        XXL: '200px',
        XL: '100px',
        L: '75px',
        LM: '70px',
        M: '60px',
        MS: '65px',
        S: '50px',
        XS: '40px',
        auto: 'auto',
        XXS: '25px',
        XXXS: '20px',
        SM: '30px',
        XSM: '10px',
        none: '0',
    },
    padding: {
        XL: '60px',
        L: '50px',
        M: '40px',
        S: '20px',
        XS: '15px',
        XXS: '10px',
        none: '0',
    },
};
